#!/usr/bin/perl

use 5.30.3;

my $base_file_path = "./test-issues";
my $total_files = 50;

sub compile_program {
    my $compile_command = "cargo build --release";

    say(`$compile_command`);
}

sub exec_program {
    my $cli_arguments = join(' ', @ARGV);

    my $exec_command = "./target/release/snitchrs $cli_arguments";

    print(`$exec_command`);
}

sub create_untagged_issues {
    my @range = (1..$total_files);
    foreach(@range) {
        my $filename = "$base_file_path/issue$_";
        my $command = "cp $base_file_path/base.txt $filename.rs";
        my $result = `$command`;
    }
}

sub create_completed_issues {
    my $command = "sed -i \"\" 's/TODO/DONE/g' ./test-issues/*.rs";

    say(`$command`);
}

sub delete_db {
    my $command = "rm ./snitch-rs.sqlite";

    say(`$command`);
}

sub test_flow {
    # Step 1: Compile
    compile_program();
    # Step 2: Test untagged issues
    create_untagged_issues();
    exec_program();
    # Step 3: Test completed issues
    create_completed_issues();
    exec_program();
    # Step 4: Clean up
    delete_db();
}

sub compile_and_run {
    compile_program();
    exec_program();
}

my $action_map =  {
    test => \&test_flow,
    compile => \&compile_program,
    default => \&compile_and_run
};

my ($action) = @ARGV;

my $has_valid_action = grep(/$action/, keys %$action_map);
$action_map->{($has_valid_action ? $action : "default" )}()